### ISSUE TITLE
Readme.md browser example: t is not defined

### ISSUE THREAD

**Issue by Juleffel** [vasturiano/aframe-forcegraph-component#11]
Hi again ! :)

Just a short issue to warn you: Your short example on the README doesn't work anymore if you don't have a `<a-camera />` defined in your `<a-scene>`, and then bug with an error difficult to understand (`t is not defined`).

Also, you could take advantage of this README change to update the version of aframe in this example (0.8.2).

Thanks again for your awesome work, I'm beginning a new project, you may hear again from me soon ;)

**Comment by vasturiano** [comment]
Thanks for the heads up @Juleffel. You're totally right, I forgot about that example snippet in the readme. It's updated now. :)

Curious to see what you're building!
