### ISSUE TITLE
graph crashes / vanishes when setting new/custom component attribute

### ISSUE THREAD

**Issue by jaronimoe** [vasturiano/aframe-forcegraph-component#12]
hi, I'm currently trying to extend your forcegraph component with some functionality that would be useful to me. so far I added a laser component to use the laser's raycaster for intersecting the nodes instead of the camera vector. this already works, but now I try to find a relatively elegant or non-hacky way of switching between camera vector and the laser's raycaster.
for my current solution, I added a "useLaserRay":boolean entry to the schema list of the forcegraph component.
however when I call 
`        var fgraph =  document.querySelector('a-entity[forcegraph]');
         fgraph.setAttribute('forcegraph', {useLaserRay: true});
`
the attribute is successfully changed but the graph vanishes without outputting any errors in the console..
this even happens when useLaserRay is not connected to any functionality - so I assume that the `         fgraph.setAttribute('forcegraph', {useLaserRay: true});` call is doing the damage... 

I added the attribute simply by extending the schema list with `useLaserRay: {type: 'boolean', default: false}` (no other changes were done..)

do you have an idea what could cause the crash?

**Comment by vasturiano** [comment]
@jaronimoe thanks for reaching out. Calling `setAttribute` on a DOM element will override the current attribute value. If you're doing `setAttribute('forcegraph', {useLaserRay: true})` possibly all the other forcegraph props are removed and replaced with a single one: `useLaserRay`. Could that be the reason why the graph is disappearing?

**Comment by jaronimoe** [comment]
that sounds plausible.. thank you for the swift reply!
I tried to call setAttribute directly on the foregraph element
`fgraph.components.forcegraph.el.setAttribute('useLaserRay', true)`
however, the field does not change.

I solved this now with directly accessing the attribute via
`fgraph.components.forcegraph.data.useLaserRay = true;`
