### ISSUE TITLE
Is graphdata from the 3d and 2d forcegraph libraries supported

### ISSUE THREAD

**Issue by aoighost** [vasturiano/aframe-forcegraph-component#15]
I'm trying to make a dynamic graph that you can add and remove nodes from the graph and I was wondering if graphdata from the other versions of the library is supported, or how to do it in general?

**Comment by vasturiano** [comment]
@aoighost thanks for reaching out. You can just manipulate the `nodes` and `links` attributes in the `forcegraph` entity. Each time those values change, the graph should automatically update.

**Comment by aoighost** [comment]
Do I have to include all the existing nodes/edges, or just the new ones or the ones that need to be deleted?

**Comment by vasturiano** [comment]
@aoighost you should maintain the state yourself of which nodes/links should be shown at a given time, and pass those lists as component props. 
Keep in mind the component does not make a defensive copy of the data, it just reads the state from the input parameters. So, any data addition/removal/update should happen outside the lib and can be easily done with array manipulation native methods.
