### ISSUE TITLE
node / link color

### ISSUE THREAD

**Issue by jaronimoe** [vasturiano/aframe-forcegraph-component#18]
hey there,

I was trying to generate a color gradient for my network elements that I would like to pass like you specified in the API:
link-color: color

however, I have no idea in which format to store the color in the json object...
I tried hexadecimal code with and without the "#"
and I tried rgb arrays as a string and as an array - but neither worked.

could you point me to a sample graph where color is defined by node/link in the json specification?

thank you!

**Comment by vasturiano** [comment]
@jaronimoe if you set `link-color: color` each of your items in the links array is expected to have a `color` attribute. Like so:
```
{
  nodes: [...],
  links: [
    { source: "...", target: "...", color: "rgb(255, 0, 0)"  },
    ...
  ]
}
```

**Comment by jaronimoe** [comment]
ah thank you!
