### ISSUE TITLE
Camera background in AR

### ISSUE THREAD

**Issue by devhims** [vasturiano/aframe-forcegraph-component#30]
I'm trying out the basic example from the repo.  But in AR mode it doesn't have the camera background. It's plain color as seen in the screenshot below. 

<img src="https://user-images.githubusercontent.com/17825870/126090246-cc30c302-536b-4e94-84e4-6001a8046201.jpg" width="300px"/>

I'm on a Samsung S8 with Google Chrome.

**Comment by vasturiano** [comment]
@devhims thanks for reaching out.

The examples on this repo are mostly setup for a VR experience. This component can still easily be used in an AR environment however (see [3d-force-graph-ar](https://github.com/vasturiano/3d-force-graph-ar)).

If you want to use it in AR, just make sure you don't set an opaque background, like it's applied here:
https://github.com/vasturiano/aframe-forcegraph-component/blob/9035e94adb9da8e90af05f0ac7fc880f0ebfb947/examples/basic/index.html#L30

**Comment by devhims** [comment]
Thanks @vasturiano! You're right, that solved the issue.  

Another thing, in the AR mode the graph was too large, so I reduced the scale by adding  ` scale="0.01 0.01 0.01"` to the `a-entity`. It did make the graph smaller, but now the graph is not visible in the 3d view (maybe it's too small now).

You can check it out here: https://rfg-ar.glitch.me/ar-aframe.html

What do you suggest? Is there any approach to this?

**Comment by vasturiano** [comment]
@devhims glad that worked.

As for the graph sizing, if you just need to make the whole graph larger/smaller, using the scale attribute is the right approach.
On the other hand if you find that there's just too much "empty space" in between the nodes/links you can try resizing those individually, for example by increasing `node-rel-size` (for all nodes) or `node-val` (individual per node).

**Comment by devhims** [comment]
Oh, that I did. It's working perfectly in AR mode. It's that in the 3d mode nothing is visible. 

**Screenshots:**

3d 
<img src="https://user-images.githubusercontent.com/17825870/126244620-dfb0ba50-cc9d-4791-8c22-9587d94bbcd4.jpg" width="300" />

AR
<img src="https://user-images.githubusercontent.com/17825870/126244621-149bf5a7-a293-477d-946d-f7fca7387b90.jpg" width="300" />

**Comment by devhims** [comment]
Although I see it in the desktop browser - just not on mobile.

<img width="1434" alt="Screenshot 2021-07-20 at 6 17 17 AM" src="https://user-images.githubusercontent.com/17825870/126245544-bc42d0b0-e649-4df3-87e7-8136cbe3b51c.png">

**Comment by devhims** [comment]
Actually, it started working on mobile as well now. Not sure why it wasn't previously (maybe my device orientation was not correct). Thanks for your help @vasturiano! 🙏

I encounter a separate issue with the react ar example, which I'll post in the related repo.
