### ISSUE TITLE
Excluding Link(s) from Intersection

### ISSUE THREAD

**Issue by apolat2000** [vasturiano/aframe-forcegraph-component#32]
**Is your feature request related to a problem? Please describe.**
I've tried many approaches for excluding the links from raycasting intersection, since it makes it really hard to hover the nodes. After many hours of searching, I still couldn't exclude the links from raycast intersection.

**Describe the solution you'd like**
An attribute for excluding graph objects from intersection (could be named as `raycastingIsDisabled`)

**Describe alternatives you've considered**
I tried adding the attribute manually and writing a middleware function which would call the Three.js's native `THREE.Mesh.prototype.raycast` function after filtering out the intersected objects according to the attribute i added. It didn't work.

**Additional context**
A solution which is possible with the current version of the project would be very much appreciated as well. Maybe if I work on it another couple hours I will get to find it, but apparently there is no comfortable way of excluding the links from intersection.

**Comment by vasturiano** [comment]
@apolat2000 thanks for reaching out.

I have struggled with the exact same issue and couldn't find a viable solution. To me, the blocker was the fact that the output of the [getIntersection](https://aframe.io/docs/1.2.0/components/raycaster.html#events_raycaster_intersected) method on the raycaster aframe component does not output a list of intersecting objects (that could afterwards be prioritised or filtered), but a single Three object, specifically the one that is closest to the camera. In other words, unlike in native Three where you can retrieve all the intersected objects via [intersectObjects](https://threejs.org/docs/#api/en/core/Raycaster.intersectObjects), there is no equivalent `getIntersections` in Aframe. `getIntersection` is the sole method exposed in the [raycaster-intersected event](https://aframe.io/docs/1.2.0/components/raycaster.html#events_raycaster_intersected) on the Aframe raycaster component.

I attempted an alternative approach of reducing the Line object intersection precision via [raycaster.params.Line.threshold](https://threejs.org/docs/#api/en/core/Raycaster.params) (if set to `0` it should have the effect of raycaster pass-through), but afaict this param is also not exposed in the Aframe raycaster component.

**Comment by apolat2000** [comment]
@vasturiano Thank you very much for your fast reply.

I solved my problem by switching to a local copy of [aframe](https://unpkg.com/browse/aframe@1.2.0/), and searching for `new THREE.Raycaster()`, and setting the line threshold of it to zero.

Thanks for the heads up!
