### ISSUE TITLE
dag-mode attribute doesn't work

### ISSUE THREAD

**Issue by lenaalaugh** [vasturiano/aframe-forcegraph-component#41]
**Describe the bug**
The aframe forcegraph component can't handle the dag-mode attribute. When adding it, the graph can't load. No errors in the console, just no graph in sight. It does work with the forcegraph vr component. I reproduced this error on several different projects and IDEs, always with the same result.

**To Reproduce**
Add the dag-mode attribute to an example.
I took the liberty to copy your example and add the dag-mode attribute [here](https://glitch.com/edit/#!/colossal-confused-titanosaurus?path=index.html%3A39%3A26).

**Expected behavior**
The graph is visible and adapts according to the attribute.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 99.0.4844.74

**Additional context**
I haven't verified yet whether your example project contains any circles. The project I encountered this problem with does not contain circles and the behavior is the same.

**Comment by vasturiano** [comment]
Thanks for the report @lenaalaugh. This was due to a bug in component specification. I've just issued a fix for it.

**Comment by lenaalaugh** [comment]
Thank you for the fast fix!
