### ISSUE TITLE
unkpg.com hosting seems to be blown

### ISSUE THREAD

**Issue by acomathes** [vasturiano/aframe-forcegraph-component#50]
I cannot include the script using `https://unpkg.com/aframe-forcegraph-component`. When I navigate to the URL with my browser, this is the page I get:

![image](https://user-images.githubusercontent.com/4698720/229876433-dc6d15a8-3a2f-4b6a-80ee-e685f366582d.png)

**Comment by vasturiano** [comment]
@apolat2000 you can get it from a different CDN, like:
https://cdn.jsdelivr.net/npm/aframe-forcegraph-component
